# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

	fileSystems."/mnt/localPersist".neededForBoot = true;

  fileSystems."/" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7CF7-97A1";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/b3313e56-ad65-46e4-adcc-fe1e6a0bd68b";
      fsType = "ext4";
    };

  fileSystems."/mnt/localPersist" =
    { device = "/dev/disk/by-uuid/7c48ae10-0de7-4e2c-b8d8-aef7727e9de0";
      fsType = "ext4";
    };

#  fileSystems."/mnt/localLuks" =
#    { device = "/dev/disk/by-uuid/07c64eff-6050-4bf1-af66-cb37db51a1ad";
#      fsType = "ext4";
#    };

#  boot.initrd.luks.devices."localLuks".device = "/dev/disk/by-uuid/62a4105c-af79-45d0-8397-f5c244f11917";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/df7bdb3c-315e-42c1-8436-1bc57b84722d"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
